### ISSUE TITLE
What is Modern C++? / Why Modern C++?

### ISSUE THREAD

**Issue by qPCR4vir** [cnjinhao/nana-handbook#1]
Hi... I will try to help. My English is not good, but... Here is my first "issue":

What is here your intention?
- Why Modern C++?  (no google search result, but could be OK if one wants to justify the choose of modern c++ as the programming language of the project.
- What is Modern C++? 
http://www.modernescpp.com/index.php/what-is-modern-c
an many other results in the web.

**Comment by cnjinhao** [comment]
Hi,
My intention is: Why should nana be developed in modern C++?

Some articles that has similar title.
Why C++ http://gamearchitect.net/Articles/WhyC++.html
Why C++ in 2017? https://blogs.msdn.microsoft.com/christophep/2017/06/26/why-c-in-2017/

**Comment by qPCR4vir** [comment]
Good: than it is:
Why Modern C++?

**Comment by qPCR4vir** [comment]
https://youtu.be/fX2W3nNjJIo?t=44m23s

**Comment by cnjinhao** [comment]
a PR(5554c2a) changed the title from "Why is Modern C++?" to "Why Modern C++"
